import { Database } from "bun:sqlite";
import { createHash, randomBytes } from "node:crypto";
import { mkdirSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { dirname } from "node:path";
import { gzipSync, gunzipSync } from "node:zlib";
import type { EngineSettings } from "../kore/runtime/types.js";
import { GameState } from "../kore/runtime/types.js";
import type { GameSettings } from "../settings/settings.js";
import type { FrozenReplayDocument, ReplayAction, ReplayDocument } from "../replay/types.js";
import { validateFrozenReplayDocument, validateReplayDocument, validateReplayOrigin } from "../replay/types.js";
import type { AuthoritativeMatchStatus, MapUsageMetric, OfflineModeMetric, PersistedMatchLifecycle } from "./types.js";
import { validateMapDocument, type MapDocument } from "../contracts/documents.js";
import type { OfflineMatchReport } from "./offlineMatchContract.js";
import type { MatchResult } from "../rules/types.js";
import { aggregatePerformanceLogs, validateMatchPerformanceReport, type MatchPerformanceReport } from "../performance/matchPerformance.js";
import type { RuntimeLogEntry } from "../kore/runtime/runtimeLog.js";
import type { FeedbackSubmission } from "./feedback.js";
import { calculateRankedRatingChange, rankedOutcome, type RankedRating } from "./ranked.js";

export type StoredGame = {
	id: string;
	settings: EngineSettings;
	/** Immutable replay origin retained independently from the mutable live snapshot. */
	initialSettings?: GameSettings;
	users: string[];
	currentTeam: number;
	turnNumber: number;
	updatedAt: number;
	mapId?: string;
	actions?: ReplayAction[];
	lifecycle?: PersistedMatchLifecycle;
	ranked?: { seasonId: string; rulesetVersion: string };
};
export type StoredFeedback = FeedbackSubmission & { id: string; createdAt: number };
export type StoredReplayShare = { token: string; replay: FrozenReplayDocument; createdAt: number; revokedAt: number | null };
export type PublicReplayShare = { token: string; replay: Omit<FrozenReplayDocument, "finalSettings">; createdAt: number };
/** Secret-token view generated by an authenticated operator for an active match. */
export type PublicOperatorReplayView = { token: string; replay: ReplayDocument; updatedAt: number };
/** Authenticated-operator-only replay index; it deliberately has no player or snapshot fields. */
export type OperatorReplayGameType = "player" | "ai";
export type OperatorReplaySummary = { gameId: string; gameType: OperatorReplayGameType; status: AuthoritativeMatchStatus; updatedAt: number; actionCount: number; replayToken?: string };
export type StoredMapStatus = "draft" | "approved" | "retired";
export type StoredMap = { id: string; document: MapDocument; status: StoredMapStatus; contentHash: string; createdAt: number; approvedAt: number | null };
/** Persisted offline/KI match; the validated replay document is retained in full. */
export type StoredOfflineMatch = OfflineMatchReport & { id: string; createdAt: number };
export type StoredOfflineMatchSummary = Omit<StoredOfflineMatch, "replay">;
export type DashboardPerformanceTrendPoint = { samples: number; value: number | null };
export type DashboardPerformancePeriod = { samples: number; average: number | null; median: number | null; p90: number | null; max: number | null; previousMedian: number | null; trend: DashboardPerformanceTrendPoint[] };
export type DashboardPerformanceMetrics = { today: DashboardPerformancePeriod; yesterday: DashboardPerformancePeriod; week: DashboardPerformancePeriod };
export type StoredPerformanceReport = MatchPerformanceReport & { id: string; createdAt: number; updatedAt: number };
export type StoredDashboardApiToken = { id: string; label: string; createdAt: number; lastUsedAt: number | null };
export type StoredDebugAssetToken = StoredDashboardApiToken;
export type StoredRankedRatingEvent = { id: string; matchId: string; seasonId: string; playerId: string; beforeRating: number; afterRating: number; delta: number; createdAt: number };
export type RankedFinalization = { matchId: string; seasonId: string; result: MatchResult; events: StoredRankedRatingEvent[] };
export type RankedSeason = { id: string; rulesetVersion: string; startsAt: number; endsAt: number | null; status: "scheduled" | "active" | "closed" };
export type RankedLeaderboardEntry = { playerId: string; rating: number; games: number; provisional: boolean };
const DASHBOARD_PERFORMANCE_CACHE_KEY = "latency";
const DASHBOARD_PERFORMANCE_CACHE_TTL_MS = 15_000;
type PerformanceSample = { createdAt: number; value: number };

function performanceTrend(samples: PerformanceSample[], rangeStart: number, rangeEnd: number, bucketCount: number): DashboardPerformanceTrendPoint[] {
	const bucketSize = (rangeEnd - rangeStart) / bucketCount;
	return Array.from({ length: bucketCount }, (_, index) => {
		const start = rangeStart + index * bucketSize;
		const end = index === bucketCount - 1 ? rangeEnd : start + bucketSize;
		const values = samples.filter(sample => sample.createdAt >= start && sample.createdAt < end).map(sample => sample.value).sort((a, b) => a - b);
		return { samples: values.length, value: values.length === 0 ? null : values[Math.ceil(values.length * 0.5) - 1]! };
	});
}

function isDashboardPerformanceMetrics(value: unknown): value is DashboardPerformanceMetrics {
	if (!value || typeof value !== "object") return false;
	const metrics = value as Partial<DashboardPerformanceMetrics>;
	return !!metrics.today && !!metrics.yesterday && !!metrics.week
		&& metrics.today.trend.length === 12
		&& metrics.yesterday.trend.length === 12
		&& metrics.week.trend.length === 7;
}

type StoredGameRow = {
	id: string;
	snapshot: Uint8Array;
	current_team: number;
	turn_number: number;
	updated_at: number;
	map_id: string;
};

type StoredLifecycleRow = {
	version: number;
	status: AuthoritativeMatchStatus;
	created_at: number | null;
	status_changed_at: number;
	completed_at: number | null;
};

type StoredUserRow = { user_id: string };
type StoredMapRow = { id: string; document_json: string; status: StoredMapStatus; content_hash: string; created_at: number; approved_at: number | null };
type OperatorReplayRow = { id: string; snapshot: Uint8Array; updated_at: number; status: AuthoritativeMatchStatus; token: string | null };

/**
 * Durable game storage. Snapshots are gzip-compressed JSON so inactive matches
 * consume disk space rather than live GameHandler memory.
 */
export class GameDatabase {
	private readonly db: Database;

	constructor(path: string = ":memory:") {
		if (path !== ":memory:") mkdirSync(dirname(path), { recursive: true });
		this.db = new Database(path);
		this.db.run("PRAGMA journal_mode = WAL");
		this.db.run("PRAGMA foreign_keys = ON");
		this.db.run(`
			CREATE TABLE IF NOT EXISTS dashboard_api_tokens (
				id TEXT PRIMARY KEY,
				token_hash TEXT NOT NULL UNIQUE,
				label TEXT NOT NULL,
				created_at INTEGER NOT NULL,
				last_used_at INTEGER
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS debug_asset_tokens (
				id TEXT PRIMARY KEY,
				token_hash TEXT NOT NULL UNIQUE,
				label TEXT NOT NULL,
				created_at INTEGER NOT NULL,
				last_used_at INTEGER
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS games (
				id TEXT PRIMARY KEY NOT NULL,
				snapshot BLOB NOT NULL,
				current_team INTEGER NOT NULL,
				turn_number INTEGER NOT NULL,
				updated_at INTEGER NOT NULL,
				map_id TEXT NOT NULL DEFAULT 'unknown'
			)
		`);
		this.migrateGameMapIds();
		this.db.run(`
			CREATE TABLE IF NOT EXISTS game_players (
				game_id TEXT NOT NULL,
				user_id TEXT NOT NULL,
				team INTEGER NOT NULL,
				connected INTEGER NOT NULL DEFAULT 0,
				PRIMARY KEY (game_id, user_id),
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
			)
		`);
		this.migrateGamePlayerKey();
		this.migrateGamePlayerConnection();
		this.db.run(`
			CREATE TABLE IF NOT EXISTS game_lifecycle (
				game_id TEXT PRIMARY KEY NOT NULL,
				version INTEGER NOT NULL,
				status TEXT NOT NULL CHECK (status IN ('resident', 'paused', 'sleeping', 'completed')),
				created_at INTEGER,
				status_changed_at INTEGER NOT NULL,
				completed_at INTEGER,
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS match_reports (
				id TEXT PRIMARY KEY NOT NULL,
				game_id TEXT NOT NULL,
				reporter_user_id TEXT NOT NULL,
				category TEXT NOT NULL,
				text TEXT NOT NULL,
				created_at INTEGER NOT NULL,
				UNIQUE(game_id, reporter_user_id, category),
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS user_feedback (
				id TEXT PRIMARY KEY NOT NULL,
				game_id TEXT,
				user_id TEXT,
				mode TEXT,
				map_id TEXT,
				topic TEXT,
				rating INTEGER,
				playtest INTEGER NOT NULL DEFAULT 0,
				text TEXT NOT NULL,
				created_at INTEGER NOT NULL,
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE SET NULL
			)
		`);
		const feedbackColumns = this.db.query("PRAGMA table_info(user_feedback)").all() as Array<{ name: string }>;
		if (!feedbackColumns.some(column => column.name === "topic")) this.db.run("ALTER TABLE user_feedback ADD COLUMN topic TEXT");
		if (!feedbackColumns.some(column => column.name === "rating")) this.db.run("ALTER TABLE user_feedback ADD COLUMN rating INTEGER");
		if (!feedbackColumns.some(column => column.name === "playtest")) this.db.run("ALTER TABLE user_feedback ADD COLUMN playtest INTEGER NOT NULL DEFAULT 0");
		const reportColumns = this.db.query("PRAGMA table_info(match_reports)").all() as Array<{ name: string }>;
		if (!reportColumns.some(column => column.name === "turn_number")) this.db.run("ALTER TABLE match_reports ADD COLUMN turn_number INTEGER NOT NULL DEFAULT 0");
		this.db.run(`
			CREATE TABLE IF NOT EXISTS replay_shares (
				token TEXT PRIMARY KEY NOT NULL,
				game_id TEXT NOT NULL UNIQUE,
				replay_json TEXT NOT NULL,
				created_at INTEGER NOT NULL,
				revoked_at INTEGER,
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS operator_replay_views (
				token TEXT PRIMARY KEY NOT NULL,
				game_id TEXT NOT NULL UNIQUE,
				replay_json TEXT NOT NULL,
				updated_at INTEGER NOT NULL,
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS offline_operator_replay_views (
				token TEXT PRIMARY KEY NOT NULL,
				offline_match_id TEXT NOT NULL UNIQUE,
				replay_json TEXT NOT NULL,
				updated_at INTEGER NOT NULL,
				FOREIGN KEY (offline_match_id) REFERENCES offline_matches(id) ON DELETE CASCADE
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS offline_matches (
				id TEXT PRIMARY KEY NOT NULL,
				mode TEXT NOT NULL CHECK (mode IN ('hotseat', 'human-vs-ai', 'ai-battle')),
				map_id TEXT NOT NULL,
				difficulty TEXT,
				seed INTEGER NOT NULL,
				players_json TEXT NOT NULL,
				result_json TEXT NOT NULL,
				replay_json TEXT NOT NULL,
				performance_logs_json TEXT NOT NULL DEFAULT '[]',
				playtest INTEGER NOT NULL DEFAULT 0,
				created_at INTEGER NOT NULL
			)
		`);
		try { this.db.run("ALTER TABLE offline_matches ADD COLUMN performance_logs_json TEXT NOT NULL DEFAULT '[]'"); } catch { /* Existing databases already have the column. */ }
		try { this.db.run("ALTER TABLE offline_matches ADD COLUMN playtest INTEGER NOT NULL DEFAULT 0"); } catch { /* Existing databases already have the column. */ }
		this.db.run(`
			CREATE TABLE IF NOT EXISTS game_performance_reports (
				id TEXT PRIMARY KEY NOT NULL,
				game_id TEXT NOT NULL,
				user_id TEXT NOT NULL,
				schema_version INTEGER NOT NULL,
				engine_version TEXT,
				client_json TEXT,
				summary_json TEXT NOT NULL,
				created_at INTEGER NOT NULL,
				updated_at INTEGER NOT NULL,
				UNIQUE(game_id, user_id, schema_version),
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS game_turn_performance (
				report_id TEXT NOT NULL,
				game_id TEXT NOT NULL,
				user_id TEXT NOT NULL,
				schema_version INTEGER NOT NULL,
				turn_number INTEGER NOT NULL,
				team INTEGER NOT NULL DEFAULT -1,
				metrics_json TEXT NOT NULL,
				PRIMARY KEY(report_id, turn_number, team),
				FOREIGN KEY (report_id) REFERENCES game_performance_reports(id) ON DELETE CASCADE,
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS dashboard_performance_cache (
				cache_key TEXT PRIMARY KEY NOT NULL,
				calculated_at INTEGER NOT NULL,
				metrics_json TEXT NOT NULL
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS ranked_seasons (
				id TEXT PRIMARY KEY NOT NULL,
				ruleset_version TEXT NOT NULL,
				starts_at INTEGER NOT NULL,
				ends_at INTEGER,
				status TEXT NOT NULL CHECK (status IN ('scheduled', 'active', 'closed'))
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS ranked_players (
				season_id TEXT NOT NULL,
				player_id TEXT NOT NULL,
				rating INTEGER NOT NULL,
				games INTEGER NOT NULL,
				provisional INTEGER NOT NULL,
				updated_at INTEGER NOT NULL,
				PRIMARY KEY (season_id, player_id)
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS ranked_matches (
				match_id TEXT PRIMARY KEY NOT NULL,
				season_id TEXT NOT NULL,
				result_json TEXT NOT NULL,
				finalized_at INTEGER NOT NULL
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS ranked_rating_events (
				id TEXT PRIMARY KEY NOT NULL,
				match_id TEXT NOT NULL,
				season_id TEXT NOT NULL,
				player_id TEXT NOT NULL,
				before_rating INTEGER NOT NULL,
				after_rating INTEGER NOT NULL,
				delta INTEGER NOT NULL,
				created_at INTEGER NOT NULL,
				UNIQUE (match_id, player_id),
				FOREIGN KEY (match_id) REFERENCES ranked_matches(match_id) ON DELETE CASCADE
			)
		`);
		this.db.run(`
			CREATE TABLE IF NOT EXISTS maps (
				id TEXT PRIMARY KEY NOT NULL,
				document_json TEXT NOT NULL,
				status TEXT NOT NULL CHECK (status IN ('draft', 'approved', 'retired')),
				content_hash TEXT NOT NULL,
				created_at INTEGER NOT NULL,
				approved_at INTEGER
			)
		`);
		this.migrateLegacyLifecycleRows();
		// A registry cache cannot survive a process restart. This repository is a
		// single-server deployment, so any stale resident row is sleeping now.
		this.db.query("UPDATE game_lifecycle SET status = 'sleeping', status_changed_at = ?1 WHERE status = 'resident'")
			.run(Date.now());
		this.db.run("UPDATE game_players SET connected = 0");
	}

	/** Creates a consistent SQLite image for an authenticated operator backup. */
	exportSnapshot(): Uint8Array {
		// Bun's serialize() can produce an incomplete image for a live WAL-backed
		// file database. Checkpoint first, then VACUUM INTO creates a consistent
		// backup including all committed schema pages and blobs.
		this.db.run("PRAGMA wal_checkpoint(FULL)");
		const directory = mkdtempSync("/tmp/kore-backup-");
		const backupPath = `${directory}/backup.sqlite`;
		try {
			const escapedPath = backupPath.replaceAll("'", "''");
			this.db.run(`VACUUM INTO '${escapedPath}'`);
			return new Uint8Array(readFileSync(backupPath));
		} finally {
			rmSync(directory, { recursive: true, force: true });
		}
	}

	public createGame(game: StoredGame): void {
		// The immutable origin is stored independently from the mutable live
		// snapshot. Never fabricate it from `settings`: a live snapshot from a
		// later turn is not a reproducible replay origin.
		const snapshot = compress({ settings: game.settings, initialSettings: game.initialSettings, actions: game.actions ?? [], ...(game.ranked ? { ranked: game.ranked } : {}) });
		const lifecycle = game.lifecycle ?? createLifecycle("resident", game.updatedAt, game.updatedAt);
		this.db.transaction(() => {
			this.db.query(`
				INSERT INTO games (id, snapshot, current_team, turn_number, updated_at, map_id)
				VALUES (?1, ?2, ?3, ?4, ?5, ?6)
			`).run(game.id, snapshot, game.currentTeam, game.turnNumber, game.updatedAt, game.mapId ?? "unknown");
			this.writeLifecycle(game.id, lifecycle);
			const insertPlayer = this.db.query("INSERT INTO game_players (game_id, user_id, team, connected) VALUES (?1, ?2, ?3, 0)");
			game.users.forEach((user, team) => insertPlayer.run(game.id, user, team));
		})();
	}

	public saveGame(game: StoredGame): void {
		const snapshot = compress({ settings: game.settings, initialSettings: game.initialSettings, actions: game.actions ?? [], ...(game.ranked ? { ranked: game.ranked } : {}) });
		this.db.transaction(() => {
			this.db.query(`
			UPDATE games
			SET snapshot = ?2, current_team = ?3, turn_number = ?4, updated_at = ?5, map_id = ?6
			WHERE id = ?1
			`).run(game.id, snapshot, game.currentTeam, game.turnNumber, game.updatedAt, game.mapId ?? "unknown");
			if (game.lifecycle) this.writeLifecycle(game.id, game.lifecycle);
		})();
	}

	public loadGame(id: string): StoredGame | undefined {
		const row = this.db.query("SELECT id, snapshot, current_team, turn_number, updated_at, map_id FROM games WHERE id = ?1")
			.get(id) as StoredGameRow | null;
		if (!row) return undefined;
		const users = this.db.query("SELECT user_id FROM game_players WHERE game_id = ?1 ORDER BY team ASC")
			.all(id) as StoredUserRow[];
		const lifecycle = this.getLifecycle(id);
		if (!lifecycle) throw new Error(`Missing lifecycle state for game ${id}`);
		const decompressed = decompress(row.snapshot);
		return {
			id: row.id,
			settings: decompressed.settings,
			// Missing origins stay missing: legacy rows without a stored
			// initialSettings cannot fabricate one from the live snapshot.
			initialSettings: decompressed.initialSettings,
			actions: decompressed.actions,
			users: users.map(user => user.user_id),
			currentTeam: row.current_team,
			turnNumber: row.turn_number,
			updatedAt: row.updated_at,
			mapId: row.map_id,
			...(decompressed.ranked ? { ranked: decompressed.ranked } : {}),
			lifecycle,
		};
	}

	public findGameIdForUser(userId: string): string | undefined {
		const row = this.db.query("SELECT game_id FROM game_players WHERE user_id = ?1 ORDER BY game_id LIMIT 1").get(userId) as { game_id: string } | null;
		return row?.game_id;
	}

	public findActiveGameIdForUser(userId: string): string | undefined {
		const row = this.db.query("SELECT game_players.game_id FROM game_players JOIN game_lifecycle ON game_lifecycle.game_id = game_players.game_id WHERE game_players.user_id = ?1 AND game_lifecycle.status != 'completed' ORDER BY game_players.game_id LIMIT 1").get(userId) as { game_id: string } | null;
		return row?.game_id;
	}

	public setGamePlayerConnected(gameId: string, userId: string, connected: boolean): void {
		this.db.query("UPDATE game_players SET connected = ?1 WHERE game_id = ?2 AND user_id = ?3").run(connected ? 1 : 0, gameId, userId);
	}

	private migrateGamePlayerKey(): void {
		const columns = this.db.query("PRAGMA table_info(game_players)").all() as Array<{ name: string; pk: number }>;
		const userColumn = columns.find(column => column.name === "user_id");
		if (!userColumn || userColumn.pk !== 1 || columns.some(column => column.pk === 2)) return;
		this.db.transaction(() => {
			this.db.run("ALTER TABLE game_players RENAME TO game_players_legacy");
			this.db.run(`CREATE TABLE game_players (
				game_id TEXT NOT NULL,
				user_id TEXT NOT NULL,
				team INTEGER NOT NULL,
				PRIMARY KEY (game_id, user_id),
				FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE
			)`);
			this.db.run("INSERT INTO game_players (game_id, user_id, team) SELECT game_id, user_id, team FROM game_players_legacy");
			this.db.run("DROP TABLE game_players_legacy");
		})();
	}

	private migrateGamePlayerConnection(): void {
		const columns = this.db.query("PRAGMA table_info(game_players)").all() as Array<{ name: string }>;
		if (!columns.some(column => column.name === "connected")) this.db.run("ALTER TABLE game_players ADD COLUMN connected INTEGER NOT NULL DEFAULT 0");
	}

	/** Removes an abandoned match and all membership rows through SQLite cascades. */
	public deleteGame(id: string): void {
		this.db.query("DELETE FROM games WHERE id = ?1").run(id);
	}

	public hasGame(id: string): boolean {
		return this.db.query("SELECT 1 AS found FROM games WHERE id = ?1").get(id) !== null;
	}

	public getGameTurnNumber(id: string): number {
		const row = this.db.query("SELECT turn_number FROM games WHERE id = ?1").get(id) as { turn_number: number } | null;
		if (!row) throw new Error("Unknown game");
		return row.turn_number;
	}

	public hasOfflineMatch(id: string): boolean {
		return this.db.query("SELECT 1 AS found FROM offline_matches WHERE id = ?1").get(id) !== null;
	}

	public getLifecycle(id: string): PersistedMatchLifecycle | undefined {
		const row = this.db.query(`
			SELECT version, status, created_at, status_changed_at, completed_at
			FROM game_lifecycle WHERE game_id = ?1
		`).get(id) as StoredLifecycleRow | null;
		return row ? lifecycleFromRow(row) : undefined;
	}

	public setLifecycle(id: string, lifecycle: PersistedMatchLifecycle): void {
		if (!this.hasGame(id)) throw new Error(`Unknown game ${id}`);
		this.writeLifecycle(id, lifecycle);
	}

	public getMetricCounts(): { allTime: number; offlineMatches: number; playtestMatches: number; offlineModes: OfflineModeMetric[]; playersAllTime: number; playersOnline: number; paused: number; sleeping: number } {
		const allTime = this.db.query("SELECT count(*) AS count FROM games").get() as { count: number };
		const offlineMatches = this.db.query("SELECT count(*) AS count FROM offline_matches").get() as { count: number };
		const playtestMatches = this.db.query("SELECT count(*) AS count FROM offline_matches WHERE playtest = 1").get() as { count: number };
		const playerIds = new Set((this.db.query("SELECT user_id FROM game_players").all() as Array<{ user_id: string }>).map(row => row.user_id));
		const offlinePlayers = this.db.query("SELECT players_json FROM offline_matches").all() as Array<{ players_json: string }>;
		for (const row of offlinePlayers) for (const player of JSON.parse(row.players_json) as string[]) playerIds.add(player);
		const playersAllTime = { count: playerIds.size };
		const playersOnline = this.db.query("SELECT count(DISTINCT game_players.user_id) AS count FROM game_players WHERE game_players.connected = 1").get() as { count: number };
		const statuses = this.db.query(`
			SELECT status, count(*) AS count FROM game_lifecycle
			WHERE status IN ('paused', 'sleeping') GROUP BY status
		`).all() as Array<{ status: AuthoritativeMatchStatus; count: number }>;
		const counts = new Map(statuses.map(row => [row.status, row.count]));
		const offlineModes = this.db.query("SELECT mode, count(*) AS games FROM offline_matches GROUP BY mode ORDER BY games DESC, mode ASC").all() as OfflineModeMetric[];
		return { allTime: allTime.count + offlineMatches.count, offlineMatches: offlineMatches.count, playtestMatches: playtestMatches.count, offlineModes, playersAllTime: playersAllTime.count, playersOnline: playersOnline.count, paused: counts.get("paused") ?? 0, sleeping: counts.get("sleeping") ?? 0 };
	}

	/** Lists every persisted action log for authenticated operator replay lookup. */
	public listOperatorReplays(gameId?: string): OperatorReplaySummary[] {
		const rows = (gameId === undefined
			? this.db.query("SELECT games.id, games.snapshot, games.updated_at, game_lifecycle.status, replay_shares.token FROM games JOIN game_lifecycle ON game_lifecycle.game_id = games.id LEFT JOIN replay_shares ON replay_shares.game_id = games.id AND replay_shares.revoked_at IS NULL ORDER BY games.updated_at DESC, games.id ASC").all()
			: this.db.query("SELECT games.id, games.snapshot, games.updated_at, game_lifecycle.status, replay_shares.token FROM games JOIN game_lifecycle ON game_lifecycle.game_id = games.id LEFT JOIN replay_shares ON replay_shares.game_id = games.id AND replay_shares.revoked_at IS NULL WHERE games.id = ?1 ORDER BY games.updated_at DESC, games.id ASC").all(gameId)) as OperatorReplayRow[];
		const online = rows.map(row => ({ gameId: row.id, gameType: "player" as const, status: row.status, updatedAt: row.updated_at, actionCount: decompress(row.snapshot).actions.length, ...(row.token ? { replayToken: row.token } : {}) }));
		const offlineRows = (gameId === undefined
			? this.db.query("SELECT id, mode, replay_json, created_at FROM offline_matches ORDER BY created_at DESC, id ASC").all()
			: this.db.query("SELECT id, mode, replay_json, created_at FROM offline_matches WHERE id = ?1").all(gameId)) as Array<{ id: string; mode: string; replay_json: string; created_at: number }>;
		const offline = offlineRows.flatMap(row => {
			try {
				const replay = JSON.parse(row.replay_json) as ReplayDocument;
				validateReplayDocument(replay);
				return [{ gameId: row.id, gameType: row.mode === "hotseat" ? "player" as const : "ai" as const, status: "completed" as AuthoritativeMatchStatus, updatedAt: row.created_at, actionCount: replay.actions.length }];
			} catch { return []; }
		});
		return [...online, ...offline].sort((left, right) => right.updatedAt - left.updatedAt || left.gameId.localeCompare(right.gameId));
	}

	/** Returns the deterministic replay document for any persisted match. */
	public getOperatorReplay(gameId: string): ReplayDocument | undefined {
		const game = this.loadGame(gameId);
		if (!game?.initialSettings) {
			const row = this.db.query("SELECT replay_json FROM offline_matches WHERE id = ?1").get(gameId) as { replay_json: string } | null;
			if (!row) return undefined;
			try {
				const replay = JSON.parse(row.replay_json) as ReplayDocument;
				validateReplayDocument(replay);
				validateReplayOrigin(replay);
				return structuredClone(replay);
			} catch { return undefined; }
		}
		const replay: ReplayDocument = { schemaVersion: 1, initialSettings: game.initialSettings, seed: 12345, actions: game.actions ?? [] };
		validateReplayDocument(replay);
		try {
			validateReplayOrigin(replay);
		} catch {
			// A legacy row whose origin is unknown cannot be replayed; an
			// unplayable document must never be offered to the operator.
			return undefined;
		}
		return structuredClone(replay);
	}

	/** Durable map usage, sorted so equal counts have a stable dashboard order. */
	public getMapUsageMetrics(): MapUsageMetric[] {
		const rows = this.db.query("SELECT map_id, count(*) AS games FROM (SELECT map_id FROM games UNION ALL SELECT map_id FROM offline_matches) GROUP BY map_id ORDER BY games DESC, map_id ASC")
			.all() as Array<{ map_id: string; games: number }>;
		const total = rows.reduce((sum, row) => sum + row.games, 0);
		return rows.map(row => ({ mapId: row.map_id, games: row.games, percentage: total === 0 ? 0 : Number(((row.games / total) * 100).toFixed(2)) }));
	}

	/** Combines persisted online summaries and offline runtime logs for the operator dashboard. */
	public getDashboardPerformanceMetrics(now: number = Date.now()): DashboardPerformanceMetrics {
		const cached = this.db.query("SELECT calculated_at, metrics_json FROM dashboard_performance_cache WHERE cache_key = ?1").get(DASHBOARD_PERFORMANCE_CACHE_KEY) as { calculated_at: number; metrics_json: string } | null;
		if (cached && now - cached.calculated_at < DASHBOARD_PERFORMANCE_CACHE_TTL_MS) {
			try {
				const metrics = JSON.parse(cached.metrics_json) as DashboardPerformanceMetrics;
				if (isDashboardPerformanceMetrics(metrics)) return metrics;
			} catch { /* Recalculate malformed cache rows. */ }
		}
		const day = 24 * 60 * 60 * 1_000;
		const todayStart = Math.floor(now / day) * day;
		const values = { today: [] as PerformanceSample[], yesterday: [] as PerformanceSample[], week: [] as PerformanceSample[] };
		const add = (createdAt: number, value: unknown): void => {
			if (typeof value !== "number" || !Number.isFinite(value) || value < 0 || createdAt < todayStart - 6 * day) return;
			if (createdAt >= todayStart) values.today.push({ createdAt, value });
			else if (createdAt >= todayStart - day) values.yesterday.push({ createdAt, value });
			if (createdAt >= todayStart - 6 * day) values.week.push({ createdAt, value });
		};
		const reports = this.db.query("SELECT summary_json, created_at FROM game_performance_reports").all() as Array<{ summary_json: string; created_at: number }>;
		for (const report of reports) {
			const summary = JSON.parse(report.summary_json) as { turnDurationMs?: { median?: number } };
			add(report.created_at, summary.turnDurationMs?.median);
		}
		const offline = this.db.query("SELECT performance_logs_json, created_at FROM offline_matches").all() as Array<{ performance_logs_json: string; created_at: number }>;
		for (const report of offline) {
			const logs = JSON.parse(report.performance_logs_json) as RuntimeLogEntry[];
			const summary = aggregatePerformanceLogs(logs, { gameId: "offline", userId: "offline" }).summary;
			let rawSamples = 0;
			for (const entry of logs) {
				if (entry.type !== "turn.completed" || !entry.data || typeof entry.data !== "object") continue;
				const duration = (entry.data as { turnDurationMs?: unknown; durationMs?: unknown }).turnDurationMs ?? (entry.data as { durationMs?: unknown }).durationMs;
				if (typeof duration === "number" && Number.isFinite(duration)) { add(report.created_at, duration); rawSamples++; }
			}
			if (rawSamples === 0) add(report.created_at, summary.turnDurationMs?.median);
		}
		const build = (sampleValues: PerformanceSample[], previousMedian: number | null, rangeStart: number, rangeEnd: number): DashboardPerformancePeriod => {
			if (sampleValues.length === 0) return { samples: 0, average: null, median: null, p90: null, max: null, previousMedian, trend: performanceTrend([], rangeStart, rangeEnd, rangeEnd - rangeStart === day ? 12 : 7) };
			const sorted = sampleValues.map(sample => sample.value).sort((a, b) => a - b);
			const percentile = (rank: number) => sorted[Math.min(sorted.length - 1, Math.ceil(sorted.length * rank) - 1)]!;
			return { samples: sorted.length, average: Number((sorted.reduce((sum, value) => sum + value, 0) / sorted.length).toFixed(2)), median: percentile(0.5), p90: percentile(0.9), max: sorted[sorted.length - 1]!, previousMedian, trend: performanceTrend(sampleValues, rangeStart, rangeEnd, rangeEnd - rangeStart === day ? 12 : 7) };
		};
		const yesterday = build(values.yesterday, null, todayStart - day, todayStart);
		const week = build(values.week, null, todayStart - 6 * day, todayStart + day);
		const metrics = { today: build(values.today, yesterday.median, todayStart, todayStart + day), yesterday, week };
		this.db.query("INSERT INTO dashboard_performance_cache (cache_key, calculated_at, metrics_json) VALUES (?1, ?2, ?3) ON CONFLICT(cache_key) DO UPDATE SET calculated_at = excluded.calculated_at, metrics_json = excluded.metrics_json")
			.run(DASHBOARD_PERFORMANCE_CACHE_KEY, now, JSON.stringify(metrics));
		return metrics;
	}

	public createMatchReport(gameId: string, reporterUserId: string, category: "conduct" | "technical" | "other", text: string, turnNumber: number, now: number = Date.now()): string {
		const id = crypto.randomUUID();
		this.db.query("INSERT INTO match_reports (id, game_id, reporter_user_id, category, text, turn_number, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)")
			.run(id, gameId, reporterUserId, category, text, turnNumber, now);
		return id;
	}

	public storeFeedback(feedback: FeedbackSubmission, now: number = Date.now()): StoredFeedback {
		const id = crypto.randomUUID();
		this.db.query("INSERT INTO user_feedback (id, game_id, user_id, mode, map_id, topic, rating, playtest, text, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)")
			.run(id, feedback.gameId ?? null, feedback.userId ?? null, feedback.mode ?? null, feedback.mapId ?? null, feedback.topic ?? null, feedback.rating ?? null, feedback.playtest ? 1 : 0, feedback.text.trim(), now);
		return { ...structuredClone(feedback), id, createdAt: now };
	}

	public listFeedback(limit = 100): StoredFeedback[] {
		const bounded = Math.max(1, Math.min(1_000, Math.trunc(limit)));
		const rows = this.db.query("SELECT id, game_id, user_id, mode, map_id, topic, rating, playtest, text, created_at FROM user_feedback ORDER BY created_at DESC, id ASC LIMIT ?1").all(bounded) as Array<{ id: string; game_id: string | null; user_id: string | null; mode: FeedbackSubmission["mode"] | null; map_id: string | null; topic: FeedbackSubmission["topic"] | null; rating: number | null; playtest: number; text: string; created_at: number }>;
		return rows.map(row => ({ id: row.id, ...(row.game_id ? { gameId: row.game_id } : {}), ...(row.user_id ? { userId: row.user_id } : {}), ...(row.mode ? { mode: row.mode } : {}), ...(row.map_id ? { mapId: row.map_id } : {}), ...(row.topic ? { topic: row.topic } : {}), ...(row.rating === null ? {} : { rating: row.rating }), ...(row.playtest ? { playtest: true } : {}), text: row.text, createdAt: row.created_at }));
	}

	public createRankedSeason(season: RankedSeason): RankedSeason {
		if (!season.id || !season.rulesetVersion || !Number.isSafeInteger(season.startsAt) || (season.endsAt !== null && !Number.isSafeInteger(season.endsAt))) throw new Error("Malformed ranked season");
		this.db.query("INSERT INTO ranked_seasons (id, ruleset_version, starts_at, ends_at, status) VALUES (?1, ?2, ?3, ?4, ?5)").run(season.id, season.rulesetVersion, season.startsAt, season.endsAt, season.status);
		return structuredClone(season);
	}

	public getRankedSeason(seasonId: string): RankedSeason | undefined {
		const row = this.db.query("SELECT id, ruleset_version, starts_at, ends_at, status FROM ranked_seasons WHERE id = ?1").get(seasonId) as { id: string; ruleset_version: string; starts_at: number; ends_at: number | null; status: RankedSeason["status"] } | null;
		return row ? { id: row.id, rulesetVersion: row.ruleset_version, startsAt: row.starts_at, endsAt: row.ends_at, status: row.status } : undefined;
	}

	public listRankedLeaderboard(seasonId: string, limit = 100): RankedLeaderboardEntry[] {
		const bounded = Math.max(1, Math.min(500, Math.trunc(limit)));
		const rows = this.db.query("SELECT player_id, rating, games, provisional FROM ranked_players WHERE season_id = ?1 ORDER BY rating DESC, games DESC, player_id ASC LIMIT ?2").all(seasonId, bounded) as Array<{ player_id: string; rating: number; games: number; provisional: number }>;
		return rows.map(row => ({ playerId: row.player_id, rating: row.rating, games: row.games, provisional: row.provisional !== 0 }));
	}

	public getRankedRating(seasonId: string, playerId: string): RankedRating {
		if (!seasonId || !playerId) throw new Error("Ranked season and player IDs are required");
		const row = this.db.query("SELECT rating, games, provisional FROM ranked_players WHERE season_id = ?1 AND player_id = ?2").get(seasonId, playerId) as { rating: number; games: number; provisional: number } | null;
		return row ? { rating: row.rating, games: row.games, provisional: row.provisional !== 0 } : { rating: 1000, games: 0, provisional: true };
	}

	/** Finalizes one authoritative two-player ranked result exactly once. */
	public finalizeRankedMatch(input: { matchId: string; seasonId: string; result: MatchResult; players: Array<{ playerId: string; team: number }>; now?: number }): RankedFinalization {
		if (!input.matchId || !input.seasonId || input.players.length !== 2 || input.players[0]!.playerId === input.players[1]!.playerId || input.players[0]!.team === input.players[1]!.team) throw new Error("Ranked matches require two distinct opposing players");
		const existing = this.db.query("SELECT result_json FROM ranked_matches WHERE match_id = ?1").get(input.matchId) as { result_json: string } | null;
		if (existing) return { matchId: input.matchId, seasonId: input.seasonId, result: JSON.parse(existing.result_json) as MatchResult, events: this.rankedEvents(input.matchId) };
		const now = input.now ?? Date.now();
		const first = input.players[0]!; const second = input.players[1]!;
		const firstChange = calculateRankedRatingChange(this.getRankedRating(input.seasonId, first.playerId), this.getRankedRating(input.seasonId, second.playerId), rankedOutcome(input.result, first.team));
		const secondChange = calculateRankedRatingChange(this.getRankedRating(input.seasonId, second.playerId), this.getRankedRating(input.seasonId, first.playerId), rankedOutcome(input.result, second.team));
		this.db.run("BEGIN IMMEDIATE");
		try {
			this.db.query("INSERT INTO ranked_matches (match_id, season_id, result_json, finalized_at) VALUES (?1, ?2, ?3, ?4)").run(input.matchId, input.seasonId, JSON.stringify(input.result), now);
			for (const [player, change] of [[first, firstChange], [second, secondChange]] as const) {
				this.db.query("INSERT INTO ranked_players (season_id, player_id, rating, games, provisional, updated_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6) ON CONFLICT(season_id, player_id) DO UPDATE SET rating = excluded.rating, games = excluded.games, provisional = excluded.provisional, updated_at = excluded.updated_at").run(input.seasonId, player.playerId, change.after.rating, change.after.games, change.after.provisional ? 1 : 0, now);
				this.db.query("INSERT INTO ranked_rating_events (id, match_id, season_id, player_id, before_rating, after_rating, delta, created_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)").run(crypto.randomUUID(), input.matchId, input.seasonId, player.playerId, change.before.rating, change.after.rating, change.delta, now);
			}
			this.db.run("COMMIT");
		} catch (error) { this.db.run("ROLLBACK"); throw error; }
		return { matchId: input.matchId, seasonId: input.seasonId, result: structuredClone(input.result), events: this.rankedEvents(input.matchId) };
	}

	private rankedEvents(matchId: string): StoredRankedRatingEvent[] {
		const rows = this.db.query("SELECT id, match_id, season_id, player_id, before_rating, after_rating, delta, created_at FROM ranked_rating_events WHERE match_id = ?1 ORDER BY player_id").all(matchId) as Array<{ id: string; match_id: string; season_id: string; player_id: string; before_rating: number; after_rating: number; delta: number; created_at: number }>;
		return rows.map(row => ({ id: row.id, matchId: row.match_id, seasonId: row.season_id, playerId: row.player_id, beforeRating: row.before_rating, afterRating: row.after_rating, delta: row.delta, createdAt: row.created_at }));
	}

	/** Persists one completed offline/KI match for later data analysis. */
	public storeOfflineMatch(report: OfflineMatchReport, now: number = Date.now()): StoredOfflineMatch {
		if (!Number.isSafeInteger(now) || now < 0) throw new Error("Offline match time must be a non-negative integer");
		const id = crypto.randomUUID();
		const replay = structuredClone(report.replay);
		this.db.query(`
			INSERT INTO offline_matches (id, mode, map_id, difficulty, seed, players_json, result_json, replay_json, performance_logs_json, playtest, created_at)
			VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11)
		`).run(id, report.mode, report.mapId, report.difficulty ?? null, report.seed, JSON.stringify(report.players), JSON.stringify(report.result), JSON.stringify(replay), JSON.stringify(report.performanceLogs ?? []), report.playtest ? 1 : 0, now);
		return { id, mode: report.mode, mapId: report.mapId, difficulty: report.difficulty, seed: report.seed, players: [...report.players], result: structuredClone(report.result), replay, performanceLogs: structuredClone(report.performanceLogs ?? []), ...(report.playtest ? { playtest: true } : {}), createdAt: now };
	}

	/** Stores one idempotent client performance report for a completed game. */
	public storePerformanceReport(report: MatchPerformanceReport, now: number = Date.now()): StoredPerformanceReport {
		validateMatchPerformanceReport(report);
		if (!Number.isSafeInteger(now) || now < 0) throw new Error("Performance report time must be a non-negative integer");
		if (!this.hasGame(report.gameId)) throw new Error("Unknown game");
		const lifecycle = this.getLifecycle(report.gameId);
		if (lifecycle?.status !== "completed") throw new Error("Performance reports require a completed game");
		const member = this.db.query("SELECT 1 AS found FROM game_players WHERE game_id = ?1 AND user_id = ?2").get(report.gameId, report.userId);
		if (!member) throw new Error("User does not belong to this game");
		const existing = this.db.query("SELECT id, created_at FROM game_performance_reports WHERE game_id = ?1 AND user_id = ?2 AND schema_version = ?3").get(report.gameId, report.userId, report.schemaVersion) as { id: string; created_at: number } | null;
		const id = existing?.id ?? crypto.randomUUID();
		const createdAt = existing?.created_at ?? now;
		this.db.transaction(() => {
			this.db.query(`
				INSERT INTO game_performance_reports (id, game_id, user_id, schema_version, engine_version, client_json, summary_json, created_at, updated_at)
				VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)
				ON CONFLICT(game_id, user_id, schema_version) DO UPDATE SET engine_version = excluded.engine_version, client_json = excluded.client_json, summary_json = excluded.summary_json, updated_at = excluded.updated_at
			`).run(id, report.gameId, report.userId, report.schemaVersion, report.engineVersion ?? null, report.client ? JSON.stringify(report.client) : null, JSON.stringify(report.summary), createdAt, now);
			this.db.query("DELETE FROM game_turn_performance WHERE report_id = ?1").run(id);
			const insertTurn = this.db.query("INSERT INTO game_turn_performance (report_id, game_id, user_id, schema_version, turn_number, team, metrics_json) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)");
			for (const turn of report.turns) insertTurn.run(id, report.gameId, report.userId, report.schemaVersion, turn.turnNumber, turn.team ?? -1, JSON.stringify(turn));
		})();
		return { ...structuredClone(report), id, createdAt, updatedAt: now };
	}

	public getPerformanceReport(gameId: string, userId: string, schemaVersion = 1): StoredPerformanceReport | undefined {
		const row = this.db.query("SELECT id, game_id, user_id, schema_version, engine_version, client_json, summary_json, created_at, updated_at FROM game_performance_reports WHERE game_id = ?1 AND user_id = ?2 AND schema_version = ?3").get(gameId, userId, schemaVersion) as { id: string; game_id: string; user_id: string; schema_version: number; engine_version: string | null; client_json: string | null; summary_json: string; created_at: number; updated_at: number } | null;
		if (!row) return undefined;
		const turns = this.db.query("SELECT metrics_json FROM game_turn_performance WHERE report_id = ?1 ORDER BY turn_number ASC, team ASC").all(row.id) as Array<{ metrics_json: string }>;
		const report: MatchPerformanceReport = { schemaVersion: row.schema_version as 1, gameId: row.game_id, userId: row.user_id, ...(row.engine_version ? { engineVersion: row.engine_version } : {}), ...(row.client_json ? { client: JSON.parse(row.client_json) } : {}), summary: JSON.parse(row.summary_json), turns: turns.map(turn => JSON.parse(turn.metrics_json)) };
		validateMatchPerformanceReport(report);
		return { ...report, id: row.id, createdAt: row.created_at, updatedAt: row.updated_at };
	}

	/** Lists offline match summaries (the heavy replay document is excluded). */
	public listOfflineMatches(limit: number = 100): StoredOfflineMatchSummary[] {
		const bounded = Math.max(1, Math.min(limit, 1_000));
		const rows = this.db.query("SELECT id, mode, map_id, difficulty, seed, players_json, result_json, playtest, created_at FROM offline_matches ORDER BY created_at DESC, id ASC LIMIT ?1")
			.all(bounded) as Array<{ id: string; mode: string; map_id: string; difficulty: string | null; seed: number; players_json: string; result_json: string; playtest: number; created_at: number }>;
		return rows.map(row => ({
			id: row.id,
			mode: row.mode as StoredOfflineMatch["mode"],
			mapId: row.map_id,
			difficulty: (row.difficulty ?? undefined) as StoredOfflineMatch["difficulty"],
			seed: row.seed,
			players: JSON.parse(row.players_json) as string[],
			result: JSON.parse(row.result_json) as MatchResult,
			...(row.playtest ? { playtest: true } : {}),
			createdAt: row.created_at,
		}));
	}

	/** Inserts one immutable declarative map revision. Updating a document is forbidden. */
	public createMap(input: { id: string; document: MapDocument; status?: "draft" | "approved"; now?: number }): StoredMap {
		if (!isUuid(input.id)) throw new Error("Map IDs must be immutable UUIDs");
		validateMapDocument(input.document);
		const status = input.status ?? "draft";
		const createdAt = input.now ?? Date.now();
		if (!Number.isSafeInteger(createdAt) || createdAt < 0) throw new Error("Map creation time must be a non-negative integer");
		const document = structuredClone(input.document);
		const contentHash = hashMapDocument(document);
		const approvedAt = status === "approved" ? createdAt : null;
		this.db.query("INSERT INTO maps (id, document_json, status, content_hash, created_at, approved_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6)")
			.run(input.id, JSON.stringify(document), status, contentHash, createdAt, approvedAt);
		return { id: input.id, document, status, contentHash, createdAt, approvedAt };
	}

	/** Human approval changes availability but can never change map content. */
	public approveMap(id: string, now: number = Date.now()): StoredMap {
		if (!isUuid(id) || !Number.isSafeInteger(now) || now < 0) throw new Error("Invalid map approval request");
		if (this.db.query("UPDATE maps SET status = 'approved', approved_at = ?2 WHERE id = ?1 AND status = 'draft'").run(id, now).changes !== 1) throw new Error("Only an existing draft map may be approved");
		return this.getMap(id)!;
	}

	/** Retired revisions remain readable for existing snapshots but are not selectable. */
	public retireMap(id: string): StoredMap {
		if (!isUuid(id)) throw new Error("Invalid map ID");
		if (this.db.query("UPDATE maps SET status = 'retired' WHERE id = ?1 AND status != 'retired'").run(id).changes !== 1) throw new Error("Only an existing active map may be retired");
		return this.getMap(id)!;
	}

	public getMap(id: string): StoredMap | undefined {
		if (!isUuid(id)) return undefined;
		const row = this.db.query("SELECT id, document_json, status, content_hash, created_at, approved_at FROM maps WHERE id = ?1").get(id) as StoredMapRow | null;
		if (!row) return undefined;
		try {
			const document = JSON.parse(row.document_json) as MapDocument;
			validateMapDocument(document);
			if (hashMapDocument(document) !== row.content_hash) throw new Error("Map content hash mismatch");
			return { id: row.id, document: structuredClone(document), status: row.status, contentHash: row.content_hash, createdAt: row.created_at, approvedAt: row.approved_at };
		} catch { throw new Error("Invalid stored map document"); }
	}

	public listMaps(status?: StoredMapStatus): StoredMap[] {
		const rows = (status === undefined
			? this.db.query("SELECT id, document_json, status, content_hash, created_at, approved_at FROM maps ORDER BY created_at, id").all()
			: this.db.query("SELECT id, document_json, status, content_hash, created_at, approved_at FROM maps WHERE status = ?1 ORDER BY created_at, id").all(status)) as StoredMapRow[];
		return rows.map(row => this.getMap(row.id)!);
	}

	public createReplayShare(gameId: string, replay: FrozenReplayDocument, now: number = Date.now()): StoredReplayShare {
		validateFrozenReplayDocument(replay);
		validateReplayOrigin(replay);
		const lifecycle = this.getLifecycle(gameId);
		if (lifecycle?.status !== "completed") throw new Error("Replay shares require a completed match");
		const existing = this.db.query("SELECT token, replay_json, created_at, revoked_at FROM replay_shares WHERE game_id = ?1").get(gameId) as { token: string; replay_json: string; created_at: number; revoked_at: number | null } | null;
		if (existing?.revoked_at === null) {
			try {
				const storedReplay = JSON.parse(existing.replay_json) as FrozenReplayDocument;
				validateFrozenReplayDocument(storedReplay);
				return { token: existing.token, replay: structuredClone(storedReplay), createdAt: existing.created_at, revokedAt: null };
			} catch { throw new Error("Stored replay share is invalid"); }
		}
		// `game_id` is intentionally unique. A revoked share is replaced so either
		// participant can publish a fresh token without reviving the old URL.
		if (existing) this.db.query("DELETE FROM replay_shares WHERE game_id = ?1").run(gameId);
		const token = crypto.randomUUID().replaceAll("-", "");
		this.db.query("INSERT INTO replay_shares (token, game_id, replay_json, created_at) VALUES (?1, ?2, ?3, ?4)")
			.run(token, gameId, JSON.stringify(replay), now);
		return { token, replay: structuredClone(replay), createdAt: now, revokedAt: null };
	}

	/** Public lookup intentionally omits game IDs and the frozen final snapshot. */
	public getPublicReplayShare(token: string): PublicReplayShare | undefined {
		if (!/^[a-f0-9]{32}$/.test(token)) return undefined;
		const row = this.db.query("SELECT replay_json, created_at, revoked_at FROM replay_shares WHERE token = ?1").get(token) as { replay_json: string; created_at: number; revoked_at: number | null } | null;
		if (!row || row.revoked_at !== null || row.replay_json.length > 2_000_000) return undefined;
		try {
			const replay = JSON.parse(row.replay_json) as FrozenReplayDocument;
			validateFrozenReplayDocument(replay);
			// Shares persisted before origin validation may still carry an
			// unplayable live fallback; those are treated as revoked.
			validateReplayOrigin(replay);
			const { finalSettings: _privateFinalSnapshot, ...publicReplay } = replay;
			return { token, replay: publicReplay, createdAt: row.created_at };
		} catch { return undefined; }
	}

	/** Upserts a private, operator-generated view token with the latest persisted actions. */
	public createOperatorReplayView(gameId: string, replay: ReplayDocument, now: number = Date.now()): PublicOperatorReplayView {
		validateReplayDocument(replay);
		validateReplayOrigin(replay);
		if (!this.hasGame(gameId)) {
			if (!this.hasOfflineMatch(gameId)) throw new Error("Unknown game");
			const existing = this.db.query("SELECT token FROM offline_operator_replay_views WHERE offline_match_id = ?1").get(gameId) as { token: string } | null;
			if (existing) {
				this.db.query("UPDATE offline_operator_replay_views SET replay_json = ?2, updated_at = ?3 WHERE offline_match_id = ?1").run(gameId, JSON.stringify(replay), now);
				return { token: existing.token, replay: structuredClone(replay), updatedAt: now };
			}
			const token = crypto.randomUUID().replaceAll("-", "");
			this.db.query("INSERT INTO offline_operator_replay_views (token, offline_match_id, replay_json, updated_at) VALUES (?1, ?2, ?3, ?4)").run(token, gameId, JSON.stringify(replay), now);
			return { token, replay: structuredClone(replay), updatedAt: now };
		}
		const existing = this.db.query("SELECT token FROM operator_replay_views WHERE game_id = ?1").get(gameId) as { token: string } | null;
		if (existing) {
			this.db.query("UPDATE operator_replay_views SET replay_json = ?2, updated_at = ?3 WHERE game_id = ?1").run(gameId, JSON.stringify(replay), now);
			return { token: existing.token, replay: structuredClone(replay), updatedAt: now };
		}
		const token = crypto.randomUUID().replaceAll("-", "");
		this.db.query("INSERT INTO operator_replay_views (token, game_id, replay_json, updated_at) VALUES (?1, ?2, ?3, ?4)").run(token, gameId, JSON.stringify(replay), now);
		return { token, replay: structuredClone(replay), updatedAt: now };
	}

	/** Resolves only an opaque token; game IDs and final snapshots never leave this lookup. */
	public getPublicOperatorReplayView(token: string): PublicOperatorReplayView | undefined {
		if (!/^[a-f0-9]{32}$/.test(token)) return undefined;
		const row = this.db.query("SELECT replay_json, updated_at FROM operator_replay_views WHERE token = ?1").get(token) as { replay_json: string; updated_at: number } | null;
		const offlineRow = row ?? this.db.query("SELECT replay_json, updated_at FROM offline_operator_replay_views WHERE token = ?1").get(token) as { replay_json: string; updated_at: number } | null;
		if (!offlineRow || offlineRow.replay_json.length > 2_000_000) return undefined;
		try {
			const replay = JSON.parse(offlineRow.replay_json) as ReplayDocument;
			validateReplayDocument(replay);
			// The operator may have snapshotted a legacy live fallback before
			// origin validation existed; such views are unplayable and are no
			// longer served instead of failing inside the viewer.
			validateReplayOrigin(replay);
			return { token, replay: structuredClone(replay), updatedAt: offlineRow.updated_at };
		} catch { return undefined; }
	}

	public revokeReplayShare(token: string, now: number = Date.now()): boolean {
		if (!/^[a-f0-9]{32}$/.test(token)) return false;
		return this.db.query("UPDATE replay_shares SET revoked_at = ?2 WHERE token = ?1 AND revoked_at IS NULL").run(token, now).changes > 0;
	}

	public getCompressedSnapshotSize(id: string): number | undefined {
		const row = this.db.query("SELECT length(snapshot) AS size FROM games WHERE id = ?1").get(id) as { size: number } | null;
		return row?.size;
	}

	private migrateGameMapIds(): void {
		const columns = this.db.query("PRAGMA table_info(games)").all() as Array<{ name: string }>;
		if (!columns.some(column => column.name === "map_id")) this.db.run("ALTER TABLE games ADD COLUMN map_id TEXT NOT NULL DEFAULT 'unknown'");
	}

	public close(): void { this.db.close() }

	public createDashboardApiToken(label: string): { token: string; record: StoredDashboardApiToken } {
		const normalized = label.trim().slice(0, 80) || "bot";
		const token = `kore_${randomBytes(32).toString("base64url")}`;
		const id = crypto.randomUUID();
		const createdAt = Date.now();
		this.db.query("INSERT INTO dashboard_api_tokens (id, token_hash, label, created_at) VALUES (?1, ?2, ?3, ?4)").run(id, createHash("sha256").update(token).digest("hex"), normalized, createdAt);
		return { token, record: { id, label: normalized, createdAt, lastUsedAt: null } };
	}
	public listDashboardApiTokens(): StoredDashboardApiToken[] {
		return this.db.query("SELECT id, label, created_at, last_used_at FROM dashboard_api_tokens ORDER BY created_at DESC").all().map(row => { const value = row as { id: string; label: string; created_at: number; last_used_at: number | null }; return { id: value.id, label: value.label, createdAt: value.created_at, lastUsedAt: value.last_used_at }; });
	}
	public revokeDashboardApiToken(id: string): boolean { return this.db.query("DELETE FROM dashboard_api_tokens WHERE id = ?1").run(id).changes > 0; }
	public isDashboardApiTokenValid(token: string): boolean {
		const hash = createHash("sha256").update(token).digest("hex");
		const row = this.db.query("SELECT id FROM dashboard_api_tokens WHERE token_hash = ?1").get(hash) as { id: string } | null;
		if (!row) return false;
		this.db.query("UPDATE dashboard_api_tokens SET last_used_at = ?2 WHERE id = ?1").run(row.id, Date.now());
		return true;
	}
	public createDebugAssetToken(label: string): { token: string; record: StoredDebugAssetToken } {
		const normalized = label.trim().slice(0, 80) || "designer";
		const token = `kore_asset_${randomBytes(32).toString("base64url")}`;
		const id = crypto.randomUUID();
		const createdAt = Date.now();
		this.db.query("INSERT INTO debug_asset_tokens (id, token_hash, label, created_at) VALUES (?1, ?2, ?3, ?4)").run(id, createHash("sha256").update(token).digest("hex"), normalized, createdAt);
		return { token, record: { id, label: normalized, createdAt, lastUsedAt: null } };
	}
	public listDebugAssetTokens(): StoredDebugAssetToken[] {
		return this.db.query("SELECT id, label, created_at, last_used_at FROM debug_asset_tokens ORDER BY created_at DESC").all().map(row => { const value = row as { id: string; label: string; created_at: number; last_used_at: number | null }; return { id: value.id, label: value.label, createdAt: value.created_at, lastUsedAt: value.last_used_at }; });
	}
	public revokeDebugAssetToken(id: string): boolean { return this.db.query("DELETE FROM debug_asset_tokens WHERE id = ?1").run(id).changes > 0; }
	public isDebugAssetTokenValid(token: string): boolean {
		const hash = createHash("sha256").update(token).digest("hex");
		const row = this.db.query("SELECT id FROM debug_asset_tokens WHERE token_hash = ?1").get(hash) as { id: string } | null;
		if (!row) return false;
		this.db.query("UPDATE debug_asset_tokens SET last_used_at = ?2 WHERE id = ?1").run(row.id, Date.now());
		return true;
	}

	private writeLifecycle(id: string, lifecycle: PersistedMatchLifecycle): void {
		this.db.query(`
			INSERT INTO game_lifecycle (game_id, version, status, created_at, status_changed_at, completed_at)
			VALUES (?1, ?2, ?3, ?4, ?5, ?6)
			ON CONFLICT(game_id) DO UPDATE SET
				version = excluded.version,
				status = excluded.status,
				created_at = excluded.created_at,
				status_changed_at = excluded.status_changed_at,
				completed_at = excluded.completed_at
		`).run(id, lifecycle.version, lifecycle.status, lifecycle.createdAt, lifecycle.statusChangedAt, lifecycle.completedAt);
	}

	private migrateLegacyLifecycleRows(): void {
		const rows = this.db.query(`
			SELECT games.id, games.snapshot, games.updated_at
			FROM games LEFT JOIN game_lifecycle ON games.id = game_lifecycle.game_id
			WHERE game_lifecycle.game_id IS NULL
		`).all() as Array<{ id: string; snapshot: Uint8Array; updated_at: number }>;
		this.db.transaction(() => {
			for (const row of rows) {
				let status: AuthoritativeMatchStatus = "sleeping";
				let completedAt: number | null = null;
				try {
					const settings = decompress(row.snapshot).settings;
					if (settings.state === GameState.Game_over && settings.matchResult) {
						status = "completed";
						completedAt = row.updated_at;
					}
				} catch {
					// Preserve malformed legacy snapshots for the existing load boundary.
				}
				this.writeLifecycle(row.id, {
					version: 1,
					status,
					createdAt: null,
					statusChangedAt: row.updated_at,
					completedAt,
				});
			}
		})();
	}
}

function createLifecycle(status: AuthoritativeMatchStatus, createdAt: number | null, statusChangedAt: number): PersistedMatchLifecycle {
	return {
		version: 1,
		status,
		createdAt,
		statusChangedAt,
		completedAt: status === "completed" ? statusChangedAt : null,
	};
}

function lifecycleFromRow(row: StoredLifecycleRow): PersistedMatchLifecycle {
	if (row.version !== 1) throw new Error(`Unsupported match lifecycle version ${row.version}`);
	if (row.status !== "resident" && row.status !== "paused" && row.status !== "sleeping" && row.status !== "completed") {
		throw new Error("Invalid persisted match lifecycle status");
	}
	return {
		version: 1,
		status: row.status,
		createdAt: row.created_at,
		statusChangedAt: row.status_changed_at,
		completedAt: row.completed_at,
	};
}

function compress(data: { settings: EngineSettings; initialSettings?: GameSettings; actions: ReplayAction[] }): Uint8Array {
	return gzipSync(JSON.stringify(data));
}

function decompress(snapshot: Uint8Array): { settings: EngineSettings; initialSettings?: GameSettings; actions: ReplayAction[]; ranked?: { seasonId: string; rulesetVersion: string } } {
	const parsed = JSON.parse(gunzipSync(snapshot).toString());
	if (parsed && typeof parsed === "object" && "settings" in parsed) {
		return { settings: parsed.settings as EngineSettings, initialSettings: parsed.initialSettings as GameSettings | undefined, actions: (parsed.actions ?? []) as ReplayAction[], ranked: parsed.ranked as { seasonId: string; rulesetVersion: string } | undefined };
	}
	return { settings: parsed as EngineSettings, actions: [] };
}

export function hashMapDocument(document: MapDocument): string {
	return createHash("sha256").update(canonicalJson(document)).digest("hex");
}

function canonicalJson(value: unknown): string {
	if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value);
	if (typeof value === "number") {
		if (!Number.isFinite(value)) throw new Error("Map documents must contain finite JSON values");
		return JSON.stringify(value);
	}
	if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`;
	if (!value || typeof value !== "object") throw new Error("Map documents must contain JSON values");
	const record = value as Record<string, unknown>;
	return `{${Object.keys(record).sort().map(key => `${JSON.stringify(key)}:${canonicalJson(record[key])}`).join(",")}}`;
}

function isUuid(value: string): boolean {
	return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
}
