/** Machine-readable inventory for the content-selection and qualification matrix. */
export const GAMEPLAY_CONTENT_REGISTRY = {
	schemaVersion: 1,
	maps: [
		{
			id: "ice-map-v1",
			name: "Ice Map",
			source: "src/settings/iceMap.ts",
			status: "qualified",
			selection: "canonical-local-match",
			worldSize: { x: 800, y: 450 },
			teamCounts: [2],
			figuresPerTeam: [1, 2, 6],
			hazards: ["deadly-obstacle-circles"],
		},
		{
			id: "cue-clash",
			name: "Cue Clash",
			source: "src/settings/cueClashMap.ts",
			status: "blocked-from-selection",
			selection: "none",
			worldSize: "scalable",
			teamCounts: [2],
			figuresPerTeam: [1, 2, 6],
			hazards: [],
		},
		{
			id: "frostbite-arena",
			name: "Frostbite Arena",
			source: "src/settings/frostbiteArenaMap.ts",
			status: "blocked-from-selection",
			selection: "none",
			worldSize: "scalable",
			teamCounts: [2],
			figuresPerTeam: [1, 2, 6],
			hazards: [],
		},
		{
			id: "magma-cradle",
			name: "Magma Cradle",
			source: "src/settings/magmaCradleMap.ts",
			status: "blocked-from-selection",
			selection: "none",
			worldSize: "scalable",
			teamCounts: [2],
			figuresPerTeam: [1, 2, 6],
			hazards: ["force-vents", "kill-zones"],
		},
	],
	modes: [
		{
			id: "quick-slip-v1",
			name: "Quick Slip",
			source: "src/rules/modeCatalog.ts",
			status: "qualified",
			selection: "local-menu-and-online",
			teamCounts: [2],
			figuresPerTeam: [1, 2, 6],
			phases: ["physics"],
			items: "disabled",
			ai: "compatible",
		},
		{
			id: "power-rush-v1",
			name: "Power Rush",
			source: "src/rules/modeCatalog.ts",
			status: "qualified",
			selection: "local-menu-and-online",
			teamCounts: [2],
			figuresPerTeam: [1, 2, 6],
			phases: ["item", "physics"],
			items: "two-per-turn",
			ai: "compatible",
		},
		{
			id: "local-ice-duel-v1",
			name: "Local Ice Duel",
			source: "src/settings/canonicalPlayableMatch.ts",
			status: "qualified",
			selection: "local-menu",
			teamCounts: [2],
			figuresPerTeam: [1],
			phases: ["item", "physics"],
			items: "power-dash",
			ai: "none",
		},
		{
			id: "current-turn",
			name: "Current Turn",
			source: "src/rules/defaultGameModes.ts",
			status: "blocked-from-selection",
			selection: "none",
			teamCounts: [2],
			figuresPerTeam: [1, 2, 6],
			phases: ["physics"],
			items: "disabled-by-default",
			ai: "optional",
		},
	],
	ai: {
		difficulties: ["easy", "medium", "hard"],
		factory: "src/settings/settings.ts#createVersusAiGameSettings",
		status: "blocked-from-selection",
		selection: "none",
		teamCounts: [2],
		figuresPerTeam: [1, 2],
		controlledTeams: { human: [0], ai: [1] },
	},
	items: {
		catalog: "official",
		source: "src/item/officialItems.ts#createOfficialItemLoader",
		status: "blocked-from-selection",
		selection: "none",
		ids: [
			"anker",
			"durchlaessigkeit",
			"magnet",
			"falltuer",
			"power-dash",
			"verzoegerte-mine",
			"mini-wall",
			"freeze-shot",
			"switch",
			"jaegermeister-elixier",
			"vodka-zero",
		],
		selectableSets: [{ id: "power-dash", status: "qualified", usedBy: "local-ice-duel-v1" }],
		economies: ["disabled", "fixed-loadout", "map-pickup", "seeded-draw"],
	},
	platforms: [
		{ id: "browser-desktop", status: "qualified", controls: ["mouse-drag"] },
		{ id: "tauri-linux", status: "qualified", controls: ["mouse-drag"], artifact: "deb-or-binary" },
		{ id: "tauri-windows", status: "unsupported", controls: ["mouse-drag"] },
		{ id: "tauri-macos", status: "unsupported", controls: ["mouse-drag"] },
		{ id: "mobile-web", status: "unsupported", controls: ["touch-drag"] },
	],
	controls: [
		{ id: "mouse-drag", source: "src/main.ts", status: "qualified", actions: ["select", "aim", "power", "release"] },
		{ id: "keyboard", source: "src/input/actions.ts", status: "unsupported", actions: ["aim", "charge", "push", "item-use"] },
		{ id: "gamepad", source: "src/input/controller.ts", status: "unsupported", actions: ["aim", "charge", "push", "item-use"] },
		{ id: "touch-drag", source: "src/input/touch.ts", status: "unsupported", actions: ["select", "aim", "power", "release"] },
	],
} as const;

export type GameplayContentRegistry = typeof GAMEPLAY_CONTENT_REGISTRY;
export type GameplayContentStatus = "qualified" | "unsupported" | "blocked-from-selection";
