export enum AssetList {
	pointertoonbPNG,
	arena2PNG,
	slipStirkeMapIceJPG,
	penguinIdleFrame2SVG,
	copilot20260505233044PNG,
	copilot20260503025035PNG,
	slipstrikeTitelbildschirmPNG,
	magmaMapPNG,
	lavaPNG,
	billiardPNG,
	arenaPNG,
	eisMapPNG,
	billiardGrosserLochJungePNG,
	darkwoodPNG,
	eisPNG,
	billiardMapPNG,
	pictureReifenSVG,
	pictureReifenPNG,
	pictureReifenWEBP,
	picturePenguinPenguinHurtFrame2PNG,
	picturePenguinPenguinStarsFrame2WEBP,
	picturePenguinPenguinHurtFrame1WEBP,
	picturePenguinPenguinIdleFrame1WEBP,
	picturePenguinPenguinStarsFrame2PNG,
	picturePenguinPenguinIdleFrame2PNG,
	picturePenguinPenguinStarsFrame1PNG,
	picturePenguinPenguinHurtFrame2WEBP,
	picturePenguinPenguinIdleFrame1PNG,
	picturePenguinPenguinIdleFrame2WEBP,
	picturePenguinPenguinHurtFrame1PNG,
	picturePenguinPenguinStarsFrame1WEBP,
	picturePolarBearPolarBearStarsFrame2PNG,
	picturePolarBearPolarBearStarsFrame1PNG,
	picturePolarBearPolarBearStarsFrame2SVG,
	picturePolarBearPolarBearHurtFrame2WEBP,
	picturePolarBearPolarBearIdleFrame2PNG,
	picturePolarBearPolarBearIdleFrame2SVG,
	picturePolarBearPolarBearHurtFrame2SVG,
	picturePolarBearPolarBearHurtFrame1PNG,
	picturePolarBearPolarBearIdleFrame2WEBP,
	picturePolarBearPolarBearIdleFrame1PNG,
	picturePolarBearPolarBearHurtFrame2PNG,
	picturePolarBearPolarBearStarsFrame2WEBP,
	picturePolarBearPolarBearStarsFrame1SVG,
	picturePolarBearPolarBearHurtFrame1SVG,
	picturePolarBearPolarBearStarsFrame1WEBP,
	picturePolarBearPolarBearIdleFrame1WEBP,
	picturePolarBearPolarBearIdleFrame1SVG,
	picturePolarBearPolarBearHurtFrame1WEBP
}

export const AssetPaths: Record<AssetList, string> = {
	[AssetList.pointertoonbPNG]: "pointer_toon_b.png",
	[AssetList.arena2PNG]: "arena2.png",
	[AssetList.slipStirkeMapIceJPG]: "Slip_Stirke_Map_Ice.jpg",
	[AssetList.penguinIdleFrame2SVG]: "Penguin_Idle_Frame_2.svg",
	[AssetList.copilot20260505233044PNG]: "Copilot_20260505_233044.png",
	[AssetList.copilot20260503025035PNG]: "Copilot_20260503_025035.png",
	[AssetList.slipstrikeTitelbildschirmPNG]: "SlipstrikeTitelbildschirm.png",
	[AssetList.magmaMapPNG]: "MagmaMap.png",
	[AssetList.lavaPNG]: "lava.png",
	[AssetList.billiardPNG]: "billiard.png",
	[AssetList.arenaPNG]: "arena.png",
	[AssetList.eisMapPNG]: "EisMap.png",
	[AssetList.billiardGrosserLochJungePNG]: "BilliardGrosserLochJunge.png",
	[AssetList.darkwoodPNG]: "dark-wood.png",
	[AssetList.eisPNG]: "eis.png",
	[AssetList.billiardMapPNG]: "BilliardMap.png",
	[AssetList.pictureReifenSVG]: "picture/Reifen.svg",
	[AssetList.pictureReifenPNG]: "picture/Reifen.png",
	[AssetList.pictureReifenWEBP]: "picture/Reifen.webp",
	[AssetList.picturePenguinPenguinHurtFrame2PNG]: "picture/penguin/Penguin_Hurt_Frame_2.png",
	[AssetList.picturePenguinPenguinStarsFrame2WEBP]: "picture/penguin/Penguin_Stars_Frame_2.webp",
	[AssetList.picturePenguinPenguinHurtFrame1WEBP]: "picture/penguin/Penguin_Hurt_Frame_1.webp",
	[AssetList.picturePenguinPenguinIdleFrame1WEBP]: "picture/penguin/Penguin_Idle_Frame_1.webp",
	[AssetList.picturePenguinPenguinStarsFrame2PNG]: "picture/penguin/Penguin_Stars_Frame_2.png",
	[AssetList.picturePenguinPenguinIdleFrame2PNG]: "picture/penguin/Penguin_Idle_Frame_2.png",
	[AssetList.picturePenguinPenguinStarsFrame1PNG]: "picture/penguin/Penguin_Stars_Frame_1.png",
	[AssetList.picturePenguinPenguinHurtFrame2WEBP]: "picture/penguin/Penguin_Hurt_Frame_2.webp",
	[AssetList.picturePenguinPenguinIdleFrame1PNG]: "picture/penguin/Penguin_Idle_Frame_1.png",
	[AssetList.picturePenguinPenguinIdleFrame2WEBP]: "picture/penguin/Penguin_Idle_Frame_2.webp",
	[AssetList.picturePenguinPenguinHurtFrame1PNG]: "picture/penguin/Penguin_Hurt_Frame_1.png",
	[AssetList.picturePenguinPenguinStarsFrame1WEBP]: "picture/penguin/Penguin_Stars_Frame_1.webp",
	[AssetList.picturePolarBearPolarBearStarsFrame2PNG]: "picture/Polar_Bear/Polar_Bear_Stars_Frame_2.png",
	[AssetList.picturePolarBearPolarBearStarsFrame1PNG]: "picture/Polar_Bear/Polar_Bear_Stars_Frame_1.png",
	[AssetList.picturePolarBearPolarBearStarsFrame2SVG]: "picture/Polar_Bear/Polar_Bear_Stars_Frame_2.svg",
	[AssetList.picturePolarBearPolarBearHurtFrame2WEBP]: "picture/Polar_Bear/Polar_Bear_Hurt_Frame_2.webp",
	[AssetList.picturePolarBearPolarBearIdleFrame2PNG]: "picture/Polar_Bear/Polar_Bear_Idle_Frame_2.png",
	[AssetList.picturePolarBearPolarBearIdleFrame2SVG]: "picture/Polar_Bear/Polar_Bear_Idle_Frame_2.svg",
	[AssetList.picturePolarBearPolarBearHurtFrame2SVG]: "picture/Polar_Bear/Polar_Bear_Hurt_Frame_2.svg",
	[AssetList.picturePolarBearPolarBearHurtFrame1PNG]: "picture/Polar_Bear/Polar_Bear_Hurt_Frame_1.png",
	[AssetList.picturePolarBearPolarBearIdleFrame2WEBP]: "picture/Polar_Bear/Polar_Bear_Idle_Frame_2.webp",
	[AssetList.picturePolarBearPolarBearIdleFrame1PNG]: "picture/Polar_Bear/Polar_Bear_Idle_Frame_1.png",
	[AssetList.picturePolarBearPolarBearHurtFrame2PNG]: "picture/Polar_Bear/Polar_Bear_Hurt_Frame_2.png",
	[AssetList.picturePolarBearPolarBearStarsFrame2WEBP]: "picture/Polar_Bear/Polar_Bear_Stars_Frame_2.webp",
	[AssetList.picturePolarBearPolarBearStarsFrame1SVG]: "picture/Polar_Bear/Polar_Bear_Stars_Frame_1.svg",
	[AssetList.picturePolarBearPolarBearHurtFrame1SVG]: "picture/Polar_Bear/Polar_Bear_Hurt_Frame_1.svg",
	[AssetList.picturePolarBearPolarBearStarsFrame1WEBP]: "picture/Polar_Bear/Polar_Bear_Stars_Frame_1.webp",
	[AssetList.picturePolarBearPolarBearIdleFrame1WEBP]: "picture/Polar_Bear/Polar_Bear_Idle_Frame_1.webp",
	[AssetList.picturePolarBearPolarBearIdleFrame1SVG]: "picture/Polar_Bear/Polar_Bear_Idle_Frame_1.svg",
	[AssetList.picturePolarBearPolarBearHurtFrame1WEBP]: "picture/Polar_Bear/Polar_Bear_Hurt_Frame_1.webp"
};

export type AssetKey = AssetList;
